---
title: "Time Series and Forecasting Final Project"
author: "Connor O'Brien, Ross Cole, Zakir Bekenov"
date: "6/4/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction 

In this project, we will model monthly BLS jobs data 12 months out in three different ways.  

## Part One: VAR Model (Connor)
Load Pagkages
```{r results = FALSE, messages= FALSE, results='hide', echo=FALSE, warning = FALSE}
library(tseries)
library(forecast)
library(vars)
library(tidyverse)
library(lubridate)
library(dynlm)
```

Load and clean data
```{r results = FALSE, messages= FALSE, results='hide', echo=FALSE, warning = FALSE}
# Load data from our Github repository
jobs_data <- read_csv("https://raw.githubusercontent.com/co237/forecasting_final/main/jobs_data.csv")
# Format date variable
jobs_data$Month <- as.Date(jobs_data$Month, "%m/%d/%Y")
# Drop pre-June 1976 data (and April 2021) for full panel
jobs1 = jobs_data[-c(1:449),]
jobs = jobs1[c(1:538),]
jobs <- jobs[ c(1,2,3,4,5,6,8,9,10,11,12,13,14) ]
# Create Time Series
jobs_national <- ts(jobs$Jobs,
                    start = c(1976,6),
                    end = c(2021, 3),
                    frequency = 12)

tenyr <- ts(jobs$Ten_yr_Treasury,
             start = c(1976,6),
             end = c(2021, 3),
             frequency = 12)

recession <- ts(jobs$NBER_Recession,
                      start = c(1976,6),
                      end = c(2021, 3),
                      frequency = 12)

population <- ts(jobs$Population,
                start = c(1976,6),
                end = c(2021, 3),
                frequency = 12)

Ind_Production <- ts(jobs$Industrial_Production,
                 start = c(1976,6),
                 end = c(2021, 3),
                 frequency = 12)

financial_conditions <- ts(jobs$Chi_Fed_NFCI,
                     start = c(1976,6),
                     end = c(2021, 3),
                     frequency = 12)

cpi <- ts(jobs$CPI,
                           start = c(1976,6),
                           end = c(2021, 3),
                           frequency = 12)

treasury_spread <- ts(jobs$T10Y2YM,
          start = c(1976,6),
          end = c(2021, 3),
          frequency = 12)

```

Total U.S. (non-farm) employment over time:

```{r}
plot(jobs_national, ylab = "Jobs", main = "U.S. Non-Farm Employment, 1976-Today")
```

Model: VAR with one and two lag variables
```{r results = FALSE, messages= FALSE, results='hide', echo=FALSE, warning = FALSE}
VAR_data <- window(ts.union(jobs_national, tenyr, recession, population, Ind_Production, financial_conditions, cpi, treasury_spread), start = c(1976, 6), end = c(2021, 3))
VAR_est <- VAR(y =VAR_data, p = 2)
VAR_est     

```

Forecast 12 months out
```{r}
forecast_data <- forecast(VAR_est, h = 12)

forecasted_jobs <- ts(forecast_data$forecast$jobs_national$mean,
                      start = c(2021,4),
                           end = c(2022, 3),
                           frequency = 12)

jobs_since_2010 <- ts(jobs_national[404:538],
                  start = c(2010,1),
                           end = c(2021, 3),
                           frequency = 12)

seqplot.ts(jobs_since_2010, forecasted_jobs, xlab = "Jobs", main = "Actual (Black) and Forecasted (Red) U.S. Non-Famr Jobs")


```

Look-back
```{r}
VAR_data_lookback <- window(ts.union(jobs_national, tenyr, recession, population, Ind_Production, financial_conditions, cpi, treasury_spread), start = c(1976, 6), end = c(2018, 12))

VAR_est2 <- VAR(y =VAR_data_lookback, p = 2)

forecast_data_2 <- forecast(VAR_est2, h = 12)


forecasted_jobs2 <- ts(forecast_data_2$forecast$jobs_national$mean,
                      start = c(2019,1),
                           end = c(2019, 12),
                           frequency = 12)

recent_jobs <- ts(jobs_national[488:523],
                  start = c(2017,1),
                           end = c(2019, 12),
                           frequency = 12)

ts.plot(forecast_data_2$forecast$jobs_national$mean, recent_jobs,gpars = list(col = c("red", "black")))

accuracy(forecasted_jobs2, recent_jobs)
```


##  Part Two: (Ross )
Load Packages 
```{r}

```

Model
```{r}

```

## Part Three: (Zakir)
Load Packages 
```{r}

```

Model
```{r}
# model
```
